NAME = webserv_tests

CPP = c++
CPPFLAGS = -Wall -Wextra -Werror -std=c++98

SRC = 	tests/test_engine.cpp \
		srcs/http/HttpResponse.cpp\

HDR = 	srcs/http/HttpResponse.hpp\

OBJ = $(SRC:.cpp=.o)

$(info [INFO] Executing TEST Makefile)

all: $(NAME)

$(NAME): $(OBJ)
	$(CPP) $(CPPFLAGS) -o $(NAME) $(OBJ)

%.o: %.cpp $(HDR)
	$(CPP) $(CPPFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
